// Mocks generated by Mockito 5.4.6 from annotations
// in hellohive/test/feature/userProfile/domain/usecases/user_profile_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:hellohive/core/errors/failure.dart' as _i5;
import 'package:hellohive/feature/settings/domain/entities/user_profile_entities.dart'
    as _i6;
import 'package:hellohive/feature/settings/domain/repositories/user_profile_repo.dart'
    as _i3;
import 'package:hellohive/feature/settings/userProfile_core/user_profile_core.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserProfileRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProfileRepo extends _i1.Mock implements _i3.UserProfileRepo {
  MockUserProfileRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserProfileEntities>>
  getUserProfileRepo(String? UId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfileRepo, [UId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.UserProfileEntities>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.UserProfileEntities>(
                    this,
                    Invocation.method(#getUserProfileRepo, [UId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.UserProfileEntities>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> addUserProfileRepo(
    _i7.UserProfParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addUserProfileRepo, [params]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#addUserProfileRepo, [params]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> updateSingleUserProfileRepo(
    _i7.UserSingleParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateSingleUserProfileRepo, [params]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#updateSingleUserProfileRepo, [params]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> updateUserProfileRepo(
    _i7.UserProfParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfileRepo, [params]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#updateUserProfileRepo, [params]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> deleteUserProfileRepo(
    _i7.UserProfParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserProfileRepo, [params]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#deleteUserProfileRepo, [params]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Stream<_i2.Either<_i5.Failure, _i6.UserStatusEntities>> getUserStatusRepo(
    String? uId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserStatusRepo, [uId]),
            returnValue:
                _i4.Stream<
                  _i2.Either<_i5.Failure, _i6.UserStatusEntities>
                >.empty(),
          )
          as _i4.Stream<_i2.Either<_i5.Failure, _i6.UserStatusEntities>>);
}
