// Mocks generated by Mockito 5.4.6 from annotations
// in hellohive/test/feature/auth/presentation/bloc/auth_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:hellohive/core/errors/failure.dart' as _i6;
import 'package:hellohive/core/usecases/usecase.dart' as _i9;
import 'package:hellohive/feature/auth/auth_core/auth_usecase/auth_core_usecase.dart'
    as _i8;
import 'package:hellohive/feature/auth/domain/entities/auth_entities.dart'
    as _i7;
import 'package:hellohive/feature/auth/domain/repositories/auth_repositories.dart'
    as _i2;
import 'package:hellohive/feature/auth/domain/usecases/auth_usecases.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthRepositories_0 extends _i1.SmartFake
    implements _i2.AuthRepositories {
  _FakeAuthRepositories_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SignInUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInUsecase extends _i1.Mock implements _i4.SignInUsecase {
  MockSignInUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepositories get repositories =>
      (super.noSuchMethod(
            Invocation.getter(#repositories),
            returnValue: _FakeAuthRepositories_0(
              this,
              Invocation.getter(#repositories),
            ),
          )
          as _i2.AuthRepositories);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.AuthEntities>> call(
    _i8.AuthParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, _i7.AuthEntities>>.value(
                  _FakeEither_1<_i6.Failure, _i7.AuthEntities>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.AuthEntities>>);
}

/// A class which mocks [SignUpUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignUpUsecase extends _i1.Mock implements _i4.SignUpUsecase {
  MockSignUpUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepositories get repositories =>
      (super.noSuchMethod(
            Invocation.getter(#repositories),
            returnValue: _FakeAuthRepositories_0(
              this,
              Invocation.getter(#repositories),
            ),
          )
          as _i2.AuthRepositories);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.AuthEntities>> call(
    _i8.AuthParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, _i7.AuthEntities>>.value(
                  _FakeEither_1<_i6.Failure, _i7.AuthEntities>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.AuthEntities>>);
}

/// A class which mocks [SignOutUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignOutUsecase extends _i1.Mock implements _i4.SignOutUsecase {
  MockSignOutUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepositories get repositories =>
      (super.noSuchMethod(
            Invocation.getter(#repositories),
            returnValue: _FakeAuthRepositories_0(
              this,
              Invocation.getter(#repositories),
            ),
          )
          as _i2.AuthRepositories);

  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> call(_i9.NoParams? noParams) =>
      (super.noSuchMethod(
            Invocation.method(#call, [noParams]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, String>>.value(
              _FakeEither_1<_i6.Failure, String>(
                this,
                Invocation.method(#call, [noParams]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, String>>);
}

/// A class which mocks [EmailVerifiedUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockEmailVerifiedUsecase extends _i1.Mock
    implements _i4.EmailVerifiedUsecase {
  MockEmailVerifiedUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepositories get repositories =>
      (super.noSuchMethod(
            Invocation.getter(#repositories),
            returnValue: _FakeAuthRepositories_0(
              this,
              Invocation.getter(#repositories),
            ),
          )
          as _i2.AuthRepositories);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i3.Unit>> call(_i9.NoParams? noParams) =>
      (super.noSuchMethod(
            Invocation.method(#call, [noParams]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, _i3.Unit>>.value(
              _FakeEither_1<_i6.Failure, _i3.Unit>(
                this,
                Invocation.method(#call, [noParams]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i3.Unit>>);
}

/// A class which mocks [VerifyEmailUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerifyEmailUsecase extends _i1.Mock
    implements _i4.VerifyEmailUsecase {
  MockVerifyEmailUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepositories get repositories =>
      (super.noSuchMethod(
            Invocation.getter(#repositories),
            returnValue: _FakeAuthRepositories_0(
              this,
              Invocation.getter(#repositories),
            ),
          )
          as _i2.AuthRepositories);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i3.Unit>> call(_i9.NoParams? noParams) =>
      (super.noSuchMethod(
            Invocation.method(#call, [noParams]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, _i3.Unit>>.value(
              _FakeEither_1<_i6.Failure, _i3.Unit>(
                this,
                Invocation.method(#call, [noParams]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i3.Unit>>);
}

/// A class which mocks [ResetPasswordUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockResetPasswordUsecase extends _i1.Mock
    implements _i4.ResetPasswordUsecase {
  MockResetPasswordUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepositories get repositories =>
      (super.noSuchMethod(
            Invocation.getter(#repositories),
            returnValue: _FakeAuthRepositories_0(
              this,
              Invocation.getter(#repositories),
            ),
          )
          as _i2.AuthRepositories);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i3.Unit>> call(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#call, [email]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, _i3.Unit>>.value(
              _FakeEither_1<_i6.Failure, _i3.Unit>(
                this,
                Invocation.method(#call, [email]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i3.Unit>>);
}
