// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAitcIZCl6dcL815BlhK7dHXOwIYrRCTJw',
    appId: '1:632621782298:web:fb0b5405e8f03b30ce48a3',
    messagingSenderId: '632621782298',
    projectId: 'hellohive',
    authDomain: 'hellohive.firebaseapp.com',
    storageBucket: 'hellohive.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0VIT3epLcvWlRZlgUB8cb4RgW9ugEgqg',
    appId: '1:632621782298:android:e426f8497f53cb99ce48a3',
    messagingSenderId: '632621782298',
    projectId: 'hellohive',
    storageBucket: 'hellohive.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDifm7__WruoUq_QMb2cKTUFz0VEga5ioM',
    appId: '1:632621782298:ios:c5a47aee4a10ca1ece48a3',
    messagingSenderId: '632621782298',
    projectId: 'hellohive',
    storageBucket: 'hellohive.firebasestorage.app',
    iosBundleId: 'com.example.hellohive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDifm7__WruoUq_QMb2cKTUFz0VEga5ioM',
    appId: '1:632621782298:ios:c5a47aee4a10ca1ece48a3',
    messagingSenderId: '632621782298',
    projectId: 'hellohive',
    storageBucket: 'hellohive.firebasestorage.app',
    iosBundleId: 'com.example.hellohive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAitcIZCl6dcL815BlhK7dHXOwIYrRCTJw',
    appId: '1:632621782298:web:7d2c4d6a76f484bace48a3',
    messagingSenderId: '632621782298',
    projectId: 'hellohive',
    authDomain: 'hellohive.firebaseapp.com',
    storageBucket: 'hellohive.firebasestorage.app',
  );
}
