// Mocks generated by Mockito 5.4.6 from annotations
// in hellohive/test/feature/auth/data/repositories/signIn_repositories_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:hellohive/core/network/netowork_info.dart' as _i4;
import 'package:hellohive/feature/auth/auth_core/auth_usecase/auth_core_usecase.dart'
    as _i7;
import 'package:hellohive/feature/auth/data/dataSources/auth_remote_data_source.dart'
    as _i6;
import 'package:hellohive/feature/auth/data/models/auth_models.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthModels_0 extends _i1.SmartFake implements _i2.AuthModels {
  _FakeAuthModels_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUnit_1 extends _i1.SmartFake implements _i3.Unit {
  _FakeUnit_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i4.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i6.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.AuthModels> signInRemoteDataSource(_i7.AuthParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#signInRemoteDataSource, [params]),
            returnValue: _i5.Future<_i2.AuthModels>.value(
              _FakeAuthModels_0(
                this,
                Invocation.method(#signInRemoteDataSource, [params]),
              ),
            ),
          )
          as _i5.Future<_i2.AuthModels>);

  @override
  _i5.Future<_i2.AuthModels> signUpRemoteDataSource(_i7.AuthParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#signUpRemoteDataSource, [params]),
            returnValue: _i5.Future<_i2.AuthModels>.value(
              _FakeAuthModels_0(
                this,
                Invocation.method(#signUpRemoteDataSource, [params]),
              ),
            ),
          )
          as _i5.Future<_i2.AuthModels>);

  @override
  _i5.Future<void> signOutRemoteDataSource() =>
      (super.noSuchMethod(
            Invocation.method(#signOutRemoteDataSource, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.AuthModels> getAuthUserDataSource() =>
      (super.noSuchMethod(
            Invocation.method(#getAuthUserDataSource, []),
            returnValue: _i5.Future<_i2.AuthModels>.value(
              _FakeAuthModels_0(
                this,
                Invocation.method(#getAuthUserDataSource, []),
              ),
            ),
          )
          as _i5.Future<_i2.AuthModels>);

  @override
  _i5.Future<_i3.Unit> verifyEmailDataSource() =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmailDataSource, []),
            returnValue: _i5.Future<_i3.Unit>.value(
              _FakeUnit_1(this, Invocation.method(#verifyEmailDataSource, [])),
            ),
          )
          as _i5.Future<_i3.Unit>);

  @override
  _i5.Future<_i3.Unit> emailVerifiedDataSource() =>
      (super.noSuchMethod(
            Invocation.method(#emailVerifiedDataSource, []),
            returnValue: _i5.Future<_i3.Unit>.value(
              _FakeUnit_1(
                this,
                Invocation.method(#emailVerifiedDataSource, []),
              ),
            ),
          )
          as _i5.Future<_i3.Unit>);

  @override
  _i5.Future<_i3.Unit> resetPasswordDataSource(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resetPasswordDataSource, [email]),
            returnValue: _i5.Future<_i3.Unit>.value(
              _FakeUnit_1(
                this,
                Invocation.method(#resetPasswordDataSource, [email]),
              ),
            ),
          )
          as _i5.Future<_i3.Unit>);

  @override
  _i5.Future<_i3.Unit> updatePasswordDatasource(String? password) =>
      (super.noSuchMethod(
            Invocation.method(#updatePasswordDatasource, [password]),
            returnValue: _i5.Future<_i3.Unit>.value(
              _FakeUnit_1(
                this,
                Invocation.method(#updatePasswordDatasource, [password]),
              ),
            ),
          )
          as _i5.Future<_i3.Unit>);
}
