// Mocks generated by Mockito 5.4.6 from annotations
// in hellohive/test/feature/userProfile/data/repositories/get_user_profile_repo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:hellohive/core/errors/failure.dart' as _i10;
import 'package:hellohive/core/network/netowork_info.dart' as _i4;
import 'package:hellohive/feature/settings/data/dataSources/user_profile_local.dart'
    as _i8;
import 'package:hellohive/feature/settings/data/dataSources/user_profile_remote.dart'
    as _i6;
import 'package:hellohive/feature/settings/data/models/user_profile_models.dart'
    as _i2;
import 'package:hellohive/feature/settings/domain/entities/user_profile_entities.dart'
    as _i11;
import 'package:hellohive/feature/settings/domain/repositories/user_profile_repo.dart'
    as _i9;
import 'package:hellohive/feature/settings/userProfile_core/user_profile_core.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserProfileModels_0 extends _i1.SmartFake
    implements _i2.UserProfileModels {
  _FakeUserProfileModels_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUnit_1 extends _i1.SmartFake implements _i3.Unit {
  _FakeUnit_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserStatusModels_2 extends _i1.SmartFake
    implements _i2.UserStatusModels {
  _FakeUserStatusModels_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_3<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i4.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [UserProfileRemote].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProfileRemote extends _i1.Mock implements _i6.UserProfileRemote {
  MockUserProfileRemote() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.UserProfileModels> getUserProfileRemote(String? uId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfileRemote, [uId]),
            returnValue: _i5.Future<_i2.UserProfileModels>.value(
              _FakeUserProfileModels_0(
                this,
                Invocation.method(#getUserProfileRemote, [uId]),
              ),
            ),
          )
          as _i5.Future<_i2.UserProfileModels>);

  @override
  _i5.Future<_i3.Unit> addUserProfileRemote(_i7.UserProfParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#addUserProfileRemote, [params]),
            returnValue: _i5.Future<_i3.Unit>.value(
              _FakeUnit_1(
                this,
                Invocation.method(#addUserProfileRemote, [params]),
              ),
            ),
          )
          as _i5.Future<_i3.Unit>);

  @override
  _i5.Future<_i3.Unit> updateSingleUserProfileRemote(
    _i7.UserSingleParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateSingleUserProfileRemote, [params]),
            returnValue: _i5.Future<_i3.Unit>.value(
              _FakeUnit_1(
                this,
                Invocation.method(#updateSingleUserProfileRemote, [params]),
              ),
            ),
          )
          as _i5.Future<_i3.Unit>);

  @override
  _i5.Future<_i3.Unit> updateUserProfileRemote(_i7.UserProfParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfileRemote, [params]),
            returnValue: _i5.Future<_i3.Unit>.value(
              _FakeUnit_1(
                this,
                Invocation.method(#updateUserProfileRemote, [params]),
              ),
            ),
          )
          as _i5.Future<_i3.Unit>);

  @override
  _i5.Future<_i3.Unit> deleteUserProfileRemote(_i7.UserProfParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserProfileRemote, [params]),
            returnValue: _i5.Future<_i3.Unit>.value(
              _FakeUnit_1(
                this,
                Invocation.method(#deleteUserProfileRemote, [params]),
              ),
            ),
          )
          as _i5.Future<_i3.Unit>);

  @override
  _i5.Stream<_i2.UserStatusModels> getUserStatusRemote(String? uId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserStatusRemote, [uId]),
            returnValue: _i5.Stream<_i2.UserStatusModels>.empty(),
          )
          as _i5.Stream<_i2.UserStatusModels>);
}

/// A class which mocks [UserProfileLocal].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProfileLocal extends _i1.Mock implements _i8.UserProfileLocal {
  MockUserProfileLocal() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Unit> cacheUserProfileLocal(
    _i2.UserProfileModels? userProfileModels,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cacheUserProfileLocal, [userProfileModels]),
            returnValue: _i5.Future<_i3.Unit>.value(
              _FakeUnit_1(
                this,
                Invocation.method(#cacheUserProfileLocal, [userProfileModels]),
              ),
            ),
          )
          as _i5.Future<_i3.Unit>);

  @override
  _i5.Future<_i2.UserProfileModels> getUserProfileLocal() =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfileLocal, []),
            returnValue: _i5.Future<_i2.UserProfileModels>.value(
              _FakeUserProfileModels_0(
                this,
                Invocation.method(#getUserProfileLocal, []),
              ),
            ),
          )
          as _i5.Future<_i2.UserProfileModels>);

  @override
  _i5.Future<_i3.Unit> cacheUserStatusLocal(
    _i2.UserStatusModels? userStatusModels,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cacheUserStatusLocal, [userStatusModels]),
            returnValue: _i5.Future<_i3.Unit>.value(
              _FakeUnit_1(
                this,
                Invocation.method(#cacheUserStatusLocal, [userStatusModels]),
              ),
            ),
          )
          as _i5.Future<_i3.Unit>);

  @override
  _i5.Future<_i2.UserStatusModels> getUserStatusLocal() =>
      (super.noSuchMethod(
            Invocation.method(#getUserStatusLocal, []),
            returnValue: _i5.Future<_i2.UserStatusModels>.value(
              _FakeUserStatusModels_2(
                this,
                Invocation.method(#getUserStatusLocal, []),
              ),
            ),
          )
          as _i5.Future<_i2.UserStatusModels>);
}

/// A class which mocks [UserProfileRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProfileRepo extends _i1.Mock implements _i9.UserProfileRepo {
  MockUserProfileRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Either<_i10.Failure, _i11.UserProfileEntities>>
  getUserProfileRepo(String? UId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfileRepo, [UId]),
            returnValue:
                _i5.Future<
                  _i3.Either<_i10.Failure, _i11.UserProfileEntities>
                >.value(
                  _FakeEither_3<_i10.Failure, _i11.UserProfileEntities>(
                    this,
                    Invocation.method(#getUserProfileRepo, [UId]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i10.Failure, _i11.UserProfileEntities>>);

  @override
  _i5.Future<_i3.Either<_i10.Failure, _i3.Unit>> addUserProfileRepo(
    _i7.UserProfParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addUserProfileRepo, [params]),
            returnValue: _i5.Future<_i3.Either<_i10.Failure, _i3.Unit>>.value(
              _FakeEither_3<_i10.Failure, _i3.Unit>(
                this,
                Invocation.method(#addUserProfileRepo, [params]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i10.Failure, _i3.Unit>>);

  @override
  _i5.Future<_i3.Either<_i10.Failure, _i3.Unit>> updateSingleUserProfileRepo(
    _i7.UserSingleParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateSingleUserProfileRepo, [params]),
            returnValue: _i5.Future<_i3.Either<_i10.Failure, _i3.Unit>>.value(
              _FakeEither_3<_i10.Failure, _i3.Unit>(
                this,
                Invocation.method(#updateSingleUserProfileRepo, [params]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i10.Failure, _i3.Unit>>);

  @override
  _i5.Future<_i3.Either<_i10.Failure, _i3.Unit>> updateUserProfileRepo(
    _i7.UserProfParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfileRepo, [params]),
            returnValue: _i5.Future<_i3.Either<_i10.Failure, _i3.Unit>>.value(
              _FakeEither_3<_i10.Failure, _i3.Unit>(
                this,
                Invocation.method(#updateUserProfileRepo, [params]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i10.Failure, _i3.Unit>>);

  @override
  _i5.Future<_i3.Either<_i10.Failure, _i3.Unit>> deleteUserProfileRepo(
    _i7.UserProfParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserProfileRepo, [params]),
            returnValue: _i5.Future<_i3.Either<_i10.Failure, _i3.Unit>>.value(
              _FakeEither_3<_i10.Failure, _i3.Unit>(
                this,
                Invocation.method(#deleteUserProfileRepo, [params]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i10.Failure, _i3.Unit>>);

  @override
  _i5.Stream<_i3.Either<_i10.Failure, _i11.UserStatusEntities>>
  getUserStatusRepo(String? uId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserStatusRepo, [uId]),
            returnValue:
                _i5.Stream<
                  _i3.Either<_i10.Failure, _i11.UserStatusEntities>
                >.empty(),
          )
          as _i5.Stream<_i3.Either<_i10.Failure, _i11.UserStatusEntities>>);
}
